name: Create Debug artifact on demand

on: workflow_dispatch

jobs:
  Build_debug_artifact:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Java8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Write run number to properties
        run: echo ciBuildNumber=${{ github.run_number }} > ./local.properties

      - name: Build debug apk
        run: ./gradlew clean assembleDebug

      - name: Rename built artifact
        run: mv app/build/outputs/apk/debug/app-debug.apk app/build/outputs/apk/debug/Template_Debug_${{ github.run_number }}.apk

      - name: Move artifacts to proper dir
        run: |
         mkdir app/build/Template_Debug_${{ github.run_number }}
         mv app/build/outputs/* app/build/Template_Debug_${{ github.run_number }}

      - name: Upload debug artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Template_Debug_${{ github.run_number }}
          path: app/build/Template_Debug_${{ github.run_number }}

      - name: Upload debug apk
        uses: actions/upload-artifact@v1
        with:
          name: Template_Debug_${{ github.run_number }}.apk
          path: app/build/Template_Debug_${{ github.run_number }}/apk/debug/Template_Debug_${{ github.run_number }}.apk