name: Build Flavor 1 Release signed app and aab

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Load .env file
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github/workflows/parameters
          mode: normalParameters

      - name: Decode Keystore
        env:
          ENCODED_STRING: ${{ secrets.KEYSTORE }}
        run: |
          TMP_KEYSTORE_FILE_PATH="${RUNNER_TEMP}"/keystore
          mkdir "${TMP_KEYSTORE_FILE_PATH}"
          echo $ENCODED_STRING | base64 -di > "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}
          echo "${TMP_KEYSTORE_FILE_PATH}"/${{ env.KEYSTORE_FILE_NAME }}

      - name: Build Release signed aab
        run: ./gradlew ${{ env.FLAVOR1_RELEASE_SIGNED_BUNDLE_TASK_NAME }}
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Rename built aab artifact
        run: mv ${{ env.FLAVOR1_BUILT_AAB_DIR }}${{ env.FLAVOR1_BUILT_AAB_NAME }} ${{ env.FLAVOR1_BUILT_AAB_DIR }}${{ env.FLAVOR1_RENAMED_AAB_NAME }}_${{ github.run_number }}.aab

      - name: Build Release signed apk
        run: ./gradlew ${{ env.FLAVOR1_RELEASE_SIGNED_BUILD_TASK_NAME }}
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      - name: Rename built apk artifact
        run: mv ${{ env.FLAVOR1_BUILT_APK_DIR }}${{ env.FLAVOR1_BUILT_APK_NAME }} ${{ env.FLAVOR1_BUILT_APK_DIR }}${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}.apk

      - name: Move artifacts to proper dir
        run: |
          mkdir app/build/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}
          mv app/build/outputs/* app/build/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}
          mv app/build/generated/source/* app/build/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}
          mv app/build/intermediates/merged_manifests/* app/build/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}

      - name: Create archive
        run: tar -czvf app/build/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}.tar.gz app/build/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}
          path: app/build/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}

      - name: Upload release aab
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.FLAVOR1_RENAMED_AAB_NAME }}_${{ github.run_number }}.aab
          path: app/build/${{ env.FLAVOR1_RENAMED_AAB_NAME }}_${{ github.run_number }}/bundle/${{ env.FLAVOR1_FLAVOR_NAME }}Release/${{ env.FLAVOR1_RENAMED_AAB_NAME }}_${{ github.run_number }}.aab

      - name: Upload release apk
        uses: actions/upload-artifact@v1
        with:
          name: ${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}.apk
          path: app/build/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}/apk/${{ env.FLAVOR1_FLAVOR_NAME }}/release/${{ env.FLAVOR1_RENAMED_APK_NAME }}_${{ github.run_number }}.apk
